org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_version=1.0-K1
maven_group=com.industrialcrops
archives_base_name=industrial-crops-neoforge

minecraft_version=1.21.1
neoforge_version=21.1.227
jei_version=19.27.0.340
mod_id=industrialcrops
mod_name=Industrial Crops
mod_author=OFFSET Inc.
mod_description=NeoForge 1.21.1 branch of Industrial Crops.
