modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Yesaz0erq/Industrial_crops/issues"

[[mods]]
modId="industrialcrops"
version="${mod_version}"
displayName="Industrial Crops"
authors="${mod_authors}"
displayURL="https://github.com/Yesaz0erq/Industrial_crops"
logoFile="industrialcrops_logo.png"
logoBlur=false
description='''尖端工业化农作物：工业农业、作物遗传、加工、物流与能源设备。'''

[[mods]]
modId="carrote"
version="${mod_version}"
displayName="Carrote"
authors="${mod_authors}"
description='''胡罗贝：悖钢、稳态物质与悖钢设备。'''

[[mixins]]
config="industrialcrops.mixins.json"

[[dependencies.industrialcrops]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.industrialcrops]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.industrialcrops]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.industrialcrops]]
modId="geckolib"
mandatory=true
versionRange="${geckolib_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.carrote]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.carrote]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.carrote]]
modId="industrialcrops"
mandatory=true
versionRange="[${mod_version},)"
ordering="AFTER"
side="BOTH"
